# Generated by Django 2.2.7 on 2019-11-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='Brak Opisu', max_length=500)),
                ('weight', models.FloatField(default=0)),
            ],
        ),
    ]
